module.exports = {

    NO_DATA_FOUND : {type: 'error', message: 'No Data Found.'},
    ATTENDANCE_MARKED_SUCCESSFULLY: {type: 'success', message: 'Attendance Marked Successfully.'},
    UNABLE_TO_MARK_ATTENDANCE: {type: 'error', message: 'Unable to Mark Attendance. Please Contact Admin.'},
    HOLIDAY_INVALID_DATE: {type: 'error', message: 'Please provide valid Date.'},
    NO_ACTIVE_PROJECTS: {type: 'error', message: 'No Active Projects.'},
    NO_ACTIVE_PROCESS: {type: 'error', message: 'No Timesheet Process available for selected Project.'},
    LEAVE_APPLIED_SUCCESSFULLY: {type: 'success', message: 'Leave Applied Successfully.'},
    UNABLE_TO_APPLY_LEAVE: {type: 'error', message: 'Unable to Apply Leave. Please Contact Admin.'},
    UNABLE_TO_GET_LEAVE_BALANCE: {type: 'error', message: 'Unable to Get Approved Leave Balance For The User. Please Contact Admin.'},
    LEAVE_ALREADY_APPLIED: {type: 'error', message: 'Leave Already Applied For Given Date Range. Please Cancel Previous Leave And Apply Again.'},
    LEAVE_CANCELLED_SUCCESSFULLY: {type: 'success', message: 'Leave has been Cancelled Successfully.'},
    UNABLE_TO_CANCEL_LEAVE: {type: 'error', message: 'Unable to Cancel Leave. Please Contact Admin.'},
    UNABLE_TO_UPDATE_LEAVE_BALANCE: {type: 'error', message: 'Leave Cancelled. But Unable to Revert User\'s Leave Balance. Please Contact Admin.'},
    DAILY_LOG_ADDED_SUCCESSFULLY: {type: 'success', message: 'User Daily Log Details Added Successfully.'},
    DAILY_LOG_ADDING_FAILED: {type: 'error', message: 'Unable to Add User Daily Log Details. Please Contact Admin.'},
    DAILY_LOG_ALREADY_EXISTS: {type: 'error', message: 'User Daily Log Details For Given Process Already Exists.'},
    DAILY_LOG_UNABLE_TO_DELETE_ENTRY: {type: 'error', message: 'Unable to Delete User Daily Log Details. Please Contact Admin.'},
    DAILY_LOG_DELETED_SUCCESSFULLY:{type: 'success', message: 'User Daily Log Details Deleted Successfully.'},
    TIMESHEET_UPDATED_SUCCESSFULLY:{type: 'success', message: 'User Timesheet Updated Successfully.'},
    TIMESHEET_UPDATE_FAILED:{type: 'error', message: 'Unable to Update User Timesheet. Please Contact Admin.'},
    TIMESHEET_APPROVED_SUCCESSFULLY:{type: 'success', message: 'User Timesheet Approved Successfully.'},
    TIMESHEET_ATTENDANCE_APPROVE_FAILED:{type: 'warning', message: 'User Timesheet Approved; But Attendance Approval Failed. Please Contact Admin.'},
    TIMESHEET_APPROVE_FAILED:{type: 'error', message: 'Unable to Approve User\'s Timesheet. Please Contact Admin.'},
    TIMESHEET_REFERBACK_SUCCESSFULLY:{type: 'success', message: 'User Timesheet Refer Backed Successfully.'},
    TIMESHEET_REFERBACK_FAILED:{type: 'error', message: 'Unable to Refer Backed User\'s Timesheet. Please Contact Admin.'},
    HOLIDAY_ADDED_SUCCESSFULLY: {type: 'success', message: 'Holiday(s) Added Successfully.'},
    HOLIDAY_EXISTS: {type: 'error', message: 'Holiday Already Exists . Please Contact Admin.'},
    UNABLE_TO_ADD_HOLIDAY: {type: 'error', message: 'Unable to Add Holiday. Please Contact Admin.'},
    HOLIDAY_UPDATED_SUCCESSFULLY: {type: 'success', message: 'Holiday(s) Updated Successfully.'},
    UNABLE_TO_UPDATE_HOLIDAY: {type: 'error', message: 'Unable to Update Holiday. Please Contact Admin.'},
    HOLIDAY_DELETED_SUCCESSFULLY: {type: 'success', message: 'Holiday(s) Deleted Successfully.'},
    UNABLE_TO_DELETE_HOLIDAY: {type: 'error', message: 'Unable to Delete Holiday. Please Contact Admin.'},
    HOLIDAY_BLOCKED_SUCCESSFULLY: {type: 'success', message: 'Holiday(s) has been Blocked/UnBlocked Successfully.'},
    UNABLE_TO_BLOCK_HOLIDAY: {type: 'error', message: 'Unable to Block/UnBlock Holiday. Please Contact Admin.'},
    HOLIDAY_APPROVED_SUCCESSFULLY: {type: 'success', message: 'Holiday(s) has been Approved/ReferBack Successfully.'},
    UNABLE_TO_APPROVE_HOLIDAY: {type: 'error', message: 'Unable to Approved/ReferBack Holiday. Please Contact Admin.'},
    ASSIGNED_TASKS_ADDED_SUCCESSFULLY: {type: 'success', message: 'Assigned Tasks Details Added Successfully.'},
    ASSIGNED_TASKS_ADDING_FAILED: {type: 'error', message: 'Unable to Add Assigned Tasks Details. Please Contact Admin.'},
    ASSIGNED_TASKS_ALREADY_EXISTS: {type: 'error', message: 'Assigned Tasks Details For Given Process Already Exists.'},
    ASSIGNED_TASKS_UNABLE_TO_DELETE_ENTRY: {type: 'error', message: 'Unable To Delete Assigned Tasks Details. Please Contact Admin.'},
    ASSIGNED_TASKS_UNABLE_TO_FOUND: {type: 'error', message: 'Unable To Found Assigned Tasks Details For Deletion.'},
    ASSIGNED_TASKS_DELETED_SUCCESSFULLY:{type: 'success', message: 'Assigned Tasks Details Deleted Successfully.'},
    PROJECT_ASSIGNED_ADDED_SUCCESSFULLY: {type: 'success', message: 'Project Assigned Added Successfully.'},
    PROJECT_ASSIGNED_ADDING_FAILED: {type: 'error', message: 'Unable to Add Project Assigned. Please Contact Admin.'},
    PROJECT_ASSIGNED_ALREADY_EXISTS: {type: 'error', message: 'Project Assigned For Given User Already Exists.'},
    PROJECT_ASSIGNED_UNABLE_TO_DELETE_ENTRY: {type: 'error', message: 'Unable to Delete Project Assigned Details. Please Contact Admin.'},
    PROJECT_ASSIGNED_DELETED_SUCCESSFULLY:{type: 'success', message: 'Project Assigned Details Deleted Successfully.'},

}